Lab 2
dxrtyx/vyrymchuk-bohdan-IPZ-32 pull request #2
Opened 2023-09-24 18:50 UTC by dxrtyx

2023-10-07 09:51 UTC, vozniuk-lntu requested changes
1. прибрати шрифт всюди, бо він навішаний на боді
2. line-height переробити всюди на відсотки або десяткові дроби
3. там де ховер через кому focus відразу 
4. передивитись кольори з фігми (посилання хедер, переваги заголовки)
5. додай транзішн https://developer.mozilla.org/en-US/docs/Web/CSS/transition
6. в портфоліо об'єднай в одну секцію
7. в карточці проекту обгорни або зображення у ссилку або все що в лі в посилання

2023-10-07 09:51 UTC, vozniuk-lntu commented on css/styles.css
> +    font-size: 14;
14 чого?

2023-10-10 21:25 UTC, dxrtyx commented
Йшов 4 день без апрува

2023-10-11 19:18 UTC, dxrtyx commented
Йшов 5 день без апрува

2023-10-12 19:43 UTC, vozniuk-lntu approved these changes
line-height до сотих

2023-10-12 19:57 UTC, vozniuk-lntu commented
так я апрувнула, зливай

2023-10-12 20:53 UTC, merged